import math

DEVICE_ADDRESS = "F2:3C:0E:CF:1B:FA"  # Device's MAC address
CHARACTERISTIC_UUID = "6cc9e001-b908-4dc9-8a1a-9fd001a8b75c"  # Characteristic UUID
PACKET_LENGTH = 62 # Expected packet length in bytes
RAW_DATA_LENGTH = 58 # Expected bytes of contiguous raw data (accelerometer, gyroscope and magnetometer)
ACCEL_SENSITIVITY = 0.061/1000.0
GYRO_SENSITIVITY = 4.375/1000.0 ## Mod: sensitivity
MAG_SENSITIVITY = 1.5 * 100 ## Mod: sensitivity
DEG_TO_RAD = math.pi / 180.0
GRAVITY = 9.80665
SAMPLE_FREC = 20
MAX_POINTS = 100  # Number of points to display

# Sensor fusion configuration
# Supported values: "madgwick", "ekf"
FUSION_FILTER = "ekf"

# EKF noise configuration
# This file is generated by calibrate_ekf_noise.py and auto-loaded at runtime.
EKF_NOISE_FILE = "ekf_noise.json"
EKF_DEFAULT_NOISES = [0.3**2, 0.5**2, 0.8**2]